### ISSUE TITLE
Падение при спаме команд в мад через тригеры в плагине.

### ISSUE THREAD

**Issue by frostf** [tmud/tortilla#13]
Как воспроизвести:
Создаем плагин с тригером на промпт строку.
В мад уходит 3-4 команды, затем клиент падает.
**Но!** Если активировать строку ```--log('ул')``` падения не будет.
Проявляется не только при спаме какой то команды, но и просто при быстром срабатывании нескольких тригеров за короткое время.
```
local plugin = {}

function plugin.name()
  return 'Тестовый плагин на LUA'
end

function plugin.description()
  return 'Описание плагина.'
end

function plugin.version()
  return '1.0'
end

local function test(v)
  --log('ул')
  runCommand('улыбнуться')
end

function plugin.init()
  createTrigger ('%%ж %%б %%о %%м', test )
end

function plugin.release()
end

return plugin
```

**Comment by gmax79** [comment]
Исправлено в 1.09

**Comment by gmax79** [comment]
https://github.com/tmud/tortilla/releases  тут брать новую версию

**Comment by frostf** [comment]
Если в триггерах использовать регулярные выражения: ```$^[0-9]+ж [0-9]+б [0-9]+о [0-9]+м```, падения продолжаются.

**Comment by frostf** [comment]
Еще немного потестировал. Падения  наблюдаются и без регулярных выражений. И по прежнему, добавление log команды в тело функции, полностью исключает любые падения.

**Comment by frostf** [comment]
К сожалению падения продолжаются, если в примере выше поменять ```runCommand('улыбнуться')``` на ```runCommand('колдовать "лечение смертельных ран"')```.  Возможно, что эта ошибка проявляется только в Рмаде (rmud.org 3040).

**Comment by gmax79** [comment]
Ошибка локализована. Я уже понял почему происходит падение. Она воспроизводится не только в rmud. Ищу оптимальное решение.

**Comment by gmax79** [comment]
Исправлено в 1.10
https://github.com/tmud/tortilla/releases

**Comment by frostf** [comment]
Крайне редко (3-5% от общего кол-ва отправленных команд в мад), но падения все еще происходят.

**Comment by gmax79** [comment]
@frostf пока не получается повторить креш.
я использую плагин, но на Былинах и клиент пустой (без дополнительных триггеров и прочего)
За пару минут спама не было креша. Тут чего то нехватает из твоих настроек.

**Comment by frostf** [comment]
Накидал плагин, который гарантированно роняет клиент, рано или поздно. При тестировании был активен только этот плагин. Суть плагина (RMUD): жрец наблюдает за кем-то (команда наблюдать) и лечит автоматом. Если где-то что-то пропустил-ошибся, заранее прошу прощения.
[rmudhealbot.zip](https://github.com/tmud/tortilla/files/2953910/rmudhealbot.zip)

**Comment by gmax79** [comment]
@frostf попробуй эту сборку https://cloud.mail.ru/public/2Egv/jSyaAtX4r
она при при креше клиента должна создать файл с crash дампом (файл), который 
нужно прислать мне. Возможно это поможет мне найти креш.

**Comment by frostf** [comment]
Такую опцию добавить было отличной идеей.
Креш словил, дамп прилагаю [crash.zip](https://github.com/tmud/tortilla/files/3004465/crash.zip).
Интересный момент связан вот с чем. Когда появилось сообщение о креше, я не сразу нажал "ок" в появившемся окне (был афк). Клиент же продолжал работать, отправлял команды, выводил сообщения.

**Comment by gmax79** [comment]
@frostf я немного недоделал предыдущую сборку. Забыл сохранить некоторые файлы для локализации креша. Повтори креш на этой сборке https://cloud.mail.ru/public/8cbe/Ks85wqUQd
Важно, чтобы ты не перепутал ее с первой, иначе crash.dmp мне не поможет.

**Comment by frostf** [comment]
[crash2.zip](https://github.com/tmud/tortilla/files/3010026/crash2.zip)

**Comment by gmax79** [comment]
Ошибка локализована и надеюсь исправлена. Попробуй эту версию
https://cloud.mail.ru/public/MmP3/hZRzZdUmA
Если упадет высылай крешдамп.

**Comment by gmax79** [comment]
@frostf есть результаты ?

**Comment by frostf** [comment]
За 4 часа непрерывной работы, повторить креш не удалось.

**Comment by gmax79** [comment]
Этот функционал достаточно сильно замедляет клиент. Пока не вижу смысла.
