### ISSUE TITLE
Как работать с файлами в плагинах Lua?

### ISSUE THREAD

**Issue by kvirund** [tmud/tortilla#4]
Пытаюсь загрузить файл как по документации:

```lua
  local f = assert(io.open(filename, "r"))
  local t = f:read("*all")
```
Клиент пишет:
```plain
attempt to index global 'io' (a nil value)
```

**Comment by kvirund** [comment]
Похоже, что не загружаются стандартные библиотеки (`luaL_openlibs`) для `lua_State`.

**Comment by kvirund** [comment]
Аналогично, нет `string.gmatch` и `"asdf".gsub`.

**Comment by kvirund** [comment]
> Стандартные библиотеки в полном объеме через openlibs не подключаются по причине того, что в клиенте в самом Lua используются utf8 строки. Стандартные либы вроде как с ними работать не умеют.

Но ведь не обязательно использовать стандартные библиотеки только с данными от клиента. Например, в SDK нет возможности работать с двоичными файлами (я, по крайней мере не нашёл).

> Луа работает в однопотоке с клиентом. Файловые операции в игровом режиме будут тормозить клиент и возможно будут наблюдаться лаги. Это вторая причина почему нету IO.

Но это уже будет зависеть от того, как написан плагин. Например, если I/O используется только для загрузки/сохранения данных плагина - тормоза если и будут проявляться, то только во время этих загрузок/сохранения: т. е. только при подключении и отключении плагина.

> В lua SDK клиента есть loadTable, saveTable для загрузки и сохранения настроек, а также работа с XML.

А разве эти операции не будут тормозить? Плюс, это SDK сильно ограничено: работа ведётся только с текстовыми файлами. А стандартная библиотека - это не только I/O. Например, регулярных выражений сейчас тоже нет. За исключением тех, которые предоставляет клиент. Но, опять же, чем регулярные выражения, предоставляемые клиентом лучше тех, которые в Lua? Сейчас это только добавляет неудобства, т. к. они имеют несовместимый интерфейс с стандартными Lua функциями. Т. е. уже нельзя взять готовый Lua код и использовать в плагине: надо обязательно переписывать его на возможности клиента.

ИМХО, ни utf8 строки клиента (из-за которых, возможно, возникнут проблемы), ни потенциальная возможность тормозов клиента (если, например, плагин написан криво), не являются какими-то объективными причинами, почему стандартные библиотеки включать не нужно.

В крайнем случае, нельзя ли это оставить это решение пользователю? Например, добавить какой-то параметр плагину, а-ля "загружать стандартную библиотеку Lua".

**Comment by kvirund** [comment]
Список стандартных библиотек Lua: https://en.wikichip.org/wiki/Lua_Standard_Libraries

**Comment by gmax79** [comment]
> Но ведь не обязательно использовать стандартные библиотеки только с данными от клиента. Например, в SDK нет возможности работать с двоичными файлами (я, по крайней мере не нашёл).
Зачем мне работать с двоичными файлами в клиенте ? Клиент текстовый и работает с текстом. Что за задача такая, где нужны бинаринки ? Я сделал только то, что нужно было в реальных задачах.

> ИМХО, ни utf8 строки клиента (из-за которых, возможно, возникнут проблемы), ни потенциальная возможность тормозов клиента (если, например, плагин написан криво), не являются какими-то объективными причинами, почему стандартные библиотеки включать не нужно.

Именно utf8 является самой везкой причиной отказа от стандартных библиотек. Они не работают со строками в юникоде.  Это источник трудно уловимых багов. Я потом запарюсь объяснять народу почему эти либы не работают как надо или почему плагин Пети не работает у Васи.

> Но это уже будет зависеть от того, как написан плагин. Например, если I/O используется только для загрузки/сохранения данных плагина - тормоза если и будут проявляться, то только во время этих загрузок/сохранения: т. е. только при подключении и отключении плагина.

А я и написал, что будут проблемы в игровом режиме (т.е. в процессе игры), а не в момент загрузки настроек.


> В крайнем случае, нельзя ли это оставить это решение пользователю? Например, добавить какой-то параметр плагину, а-ля "загружать стандартную библиотеку Lua".

Нет нельзя. Я уже выше написал почему. Если тебе нехватает какойто фишки в луа - пиши на С++ плагин и пробрасывай методы в луа.

**Comment by gmax79** [comment]
Подключены math, table, package библиотеки.  
Необходимости в остальных нет.

**Comment by kvirund** [comment]
> Именно utf8 является самой везкой причиной отказа от стандартных библиотек. Они не работают со строками в юникоде. Это источник трудно уловимых багов.

А какие там могут быть баги? Lua просто все строки представляет как последовательность байт без какой-либо кодировки.

> Я потом запарюсь объяснять народу почему эти либы не работают как надо или почему плагин Пети не работает у Васи.

У них это будет не работать одинаково, т. к. Lua будет одинаково неподдерживать utf-8 и у Васи и у Пети.

> Если тебе нехватает какойто фишки в луа - пиши на С++ плагин и пробрасывай методы в луа.

Мне в Lua не хватает её стандартной библиотеки. Я бы с удовольствием написал плагин на C++, если бы мне не хватало чего-то, что ещё не написано. А в Lua уже всё готово и ты предлагаешь вариант вместо одного вызова `luaL_openlibs` при создании контекста Lua, переписывать всю её стандартную библиотеку. При том, что баги, если и будут, то только по вине самих плагинописателей. Это весьма не user-friendly. Тем более, что допустить ошибку при написании недостающих функций на Си - гораздо выше.

**Comment by gmax79** [comment]
> А какие там могут быть баги? Lua просто все строки представляет как последовательность байт без какой-либо кодировки.

Ты путаешь Lua (которая хранит строки как набор байт, как ты и сказал), со стандартными библиотеками ( которые работают только с ansi строками ). В клиенте все строки на юникоде, поэтому стандартные библиотеки отменяются и их точно не будет (мне не нужны в клиенте такие костыли, а это именно костыль ).

Регулярки в клиенте есть, работа с хмл есть, загрузка и сохранение есть, работа с триггерами есть. База для плагинов готова. Чего еще не хватает из стандартной библиотеки ?

**Comment by kvirund** [comment]
Мне не надо работать с клиентскими utf8 строками. Мне достаточно латинских символов.

Мне хватает интерфейса, совместимого с функциями Lua. Чтобы работали gsub, gmatch, и т. п., как они описаны в документации Lua. Костыли - это вручную писать велосипеды, типа Сишных функций, чтобы обращаться к ним из Lua, т. к. стандартная библиотека, видите ли, не поддерживает utf8.

**Comment by kvirund** [comment]
Как и задумывалось: использование стандартной библиотеки опасно в силу подмены стандартного типа `string`. Из вариантов - только расширять текущий функционал, работающий с новыми строками, либо как-то переключать контекст. Но в этом случае, вероятно, возникнет ещё бОльшая путаница.
