### ISSUE TITLE
Падение на команде "#output %0"

### ISSUE THREAD

**Issue by frostf** [tmud/tortilla#8]
Как воспроизвести:
Строка мада: **На стене**
> #action {На %1} {#output %0}

**Comment by gmax79** [comment]
Тут идет зацикливание. На строку #output опять срабатывает этот же триггер.
Так задумано что на #output срабатывают триггера. Чтобы этого не было нужно использовать #woutput 0 %0.
Как решить проблему - нужно думать.

**Comment by gmax79** [comment]
Проблему решил так.
Нв строке #output триггер сработает 1 раз. Т.е. если триггер сработал на output и там есть свой output, то он уже выдаст строку, на которую другие триггеры не сработают.
