### ISSUE TITLE
Пожелание: аналог global.set из jmc

### ISSUE THREAD

**Issue by frostf** [tmud/tortilla#9]
Не хватает общих настроек для конкретного мада. Приходиться дублировать какие то тригеры/хайлайты в каждом профиле этого мада. Как решение: добавление **группы global**. Спасибо.

**Comment by gmax79** [comment]
Общие триги легко создаются через плагин луа. Общие триги через профили требуют много дополнительных доработок в клиенте.

**Comment by frostf** [comment]
Так и поступлю. Спасибо за ответ и за отличный клиент.
